import './globals.css'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className='w-screen overflow-x-hidden bg-teal-50 pt-2 p-4'>{children}</body>
        </html>
    )
}
